/* ==========================================================================
   🎯 WHITEBOARD ENGINE - TAILWIND-STYLE CLASS TO INLINE STYLE RESOLVER
   ========================================================================== */

/* Auto-generated from master.css */

export const MASTER_STYLE_MAP = {
  'text-black': { color: '#000000' },
  'text-white': { color: '#ffffff' },
  'text-gray': { color: '#4b5563' },
  'text-light-gray': { color: '#9ca3af' },
  'text-red': { color: '#e11d48' },
  'text-blue': { color: '#1d4ed8' },
  'text-cyan': { color: '#0284c7' },
  'text-green': { color: '#10b981' },
  'text-emerald': { color: '#047857' },
  'text-purple': { color: '#7e22ce' },
  'text-fuchsia': { color: '#c026d3' },
  'text-pink': { color: '#db2777' },
  'text-orange': { color: '#ea580c' },
  'text-yellow': { color: '#d97706' },
  'bg-black': { backgroundColor: '#000000' },
  'bg-white': { backgroundColor: '#ffffff' },
  'bg-gray-50': { backgroundColor: '#f9fafb' },
  'bg-gray-100': { backgroundColor: '#f3f4f6' },
  'bg-red': { backgroundColor: '#ffe4e6' },
  'bg-blue': { backgroundColor: '#dbeafe' },
  'bg-cyan': { backgroundColor: '#e0f2fe' },
  'bg-green': { backgroundColor: '#d1fae5' },
  'bg-purple': { backgroundColor: '#f3e8ff' },
  'bg-orange': { backgroundColor: '#ffedd5' },
  'bg-yellow': { backgroundColor: '#fef9c3' },
  'text-xs': { fontSize: '16px' },
  'text-sm': { fontSize: '20px' },
  'text-base': { fontSize: '24px' },
  'text-lg': { fontSize: '28px' },
  'text-xl': { fontSize: '32px' },
  'text-2xl': { fontSize: '38px' },
  'text-3xl': { fontSize: '45px' },
  'text-4xl': { fontSize: '52px' },
  'text-5xl': { fontSize: '64px' },
  'text-6xl': { fontSize: '75px' },
  'text-7xl': { fontSize: '85px' },
  'text-8xl': { fontSize: '95px' },
  'text-9xl': { fontSize: '110px' },
  'top-0': { top: '0px' },
  'top-5': { top: '5px' },
  'top-10': { top: '10px' },
  'top-15': { top: '15px' },
  'top-20': { top: '20px' },
  'top-25': { top: '25px' },
  'top-30': { top: '30px' },
  'top-35': { top: '35px' },
  'top-40': { top: '40px' },
  'top-45': { top: '45px' },
  'top-50': { top: '50px' },
  'top-60': { top: '60px' },
  'top-70': { top: '70px' },
  'top-80': { top: '80px' },
  'top-90': { top: '90px' },
  'top-100': { top: '100px' },
  'top-110': { top: '110px' },
  'top-120': { top: '120px' },
  'top-130': { top: '130px' },
  'top-140': { top: '140px' },
  'top-150': { top: '150px' },
  'top-160': { top: '160px' },
  'top-170': { top: '170px' },
  'top-180': { top: '180px' },
  'top-190': { top: '190px' },
  'top-200': { top: '200px' },
  'top-210': { top: '210px' },
  'top-220': { top: '220px' },
  'top-230': { top: '230px' },
  'top-240': { top: '240px' },
  'top-250': { top: '250px' },
  'top-260': { top: '260px' },
  'top-270': { top: '270px' },
  'top-280': { top: '280px' },
  'top-290': { top: '290px' },
  'top-300': { top: '300px' },
  'top-350': { top: '350px' },
  'top-400': { top: '400px' },
  'top-450': { top: '450px' },
  'top-500': { top: '500px' },
  'top-550': { top: '550px' },
  'top-600': { top: '600px' },
  'top-650': { top: '650px' },
  'top-700': { top: '700px' },
  'top-750': { top: '750px' },
  'top-800': { top: '800px' },
  'top-850': { top: '850px' },
  'top-900': { top: '900px' },
  'top-950': { top: '950px' },
  'top-1000': { top: '1000px' },
  'top-1100': { top: '1100px' },
  'top-1200': { top: '1200px' },
  'left-0': { left: '0px' },
  'left-5': { left: '5px' },
  'left-10': { left: '10px' },
  'left-15': { left: '15px' },
  'left-20': { left: '20px' },
  'left-25': { left: '25px' },
  'left-30': { left: '30px' },
  'left-35': { left: '35px' },
  'left-40': { left: '40px' },
  'left-45': { left: '45px' },
  'left-50': { left: '50px' },
  'left-60': { left: '60px' },
  'left-70': { left: '70px' },
  'left-80': { left: '80px' },
  'left-90': { left: '90px' },
  'left-100': { left: '100px' },
  'left-110': { left: '110px' },
  'left-120': { left: '120px' },
  'left-130': { left: '130px' },
  'left-140': { left: '140px' },
  'left-150': { left: '150px' },
  'left-160': { left: '160px' },
  'left-170': { left: '170px' },
  'left-180': { left: '180px' },
  'left-190': { left: '190px' },
  'left-200': { left: '200px' },
  'left-220': { left: '220px' },
  'left-240': { left: '240px' },
  'left-250': { left: '250px' },
  'left-260': { left: '260px' },
  'left-280': { left: '280px' },
  'left-300': { left: '300px' },
  'left-350': { left: '350px' },
  'left-400': { left: '400px' },
  'left-450': { left: '450px' },
  'left-500': { left: '500px' },
  'left-550': { left: '550px' },
  'left-600': { left: '600px' },
  'left-650': { left: '650px' },
  'left-700': { left: '700px' },
  'left-750': { left: '750px' },
  'left-800': { left: '800px' },
  'left-850': { left: '850px' },
  'left-900': { left: '900px' },
  'left-950': { left: '950px' },
  'left-1000': { left: '1000px' },
  'left-1100': { left: '1100px' },
  'left-1200': { left: '1200px' },
  'left-1300': { left: '1300px' },
  'left-1400': { left: '1400px' },
  'left-1500': { left: '1500px' },
  'highlight-yellow': { backgroundColor: '#fef08a', borderRadius: '4px', padding: '0px 6px' },
  'highlight-purple': { backgroundColor: '#e9d5ff', borderRadius: '4px', padding: '0px 6px' },
  'highlight-green': { backgroundColor: '#a7f3d0', borderRadius: '4px', padding: '0px 6px' },
  'highlight-blue': { backgroundColor: '#bfdbfe', borderRadius: '4px', padding: '0px 6px' },
  'highlight-orange': { backgroundColor: '#ffedd5', borderRadius: '4px', padding: '0px 6px' },
  'highlight-pink': { backgroundColor: '#fbcfe8', borderRadius: '4px', padding: '0px 6px' },
  'highlight-cyan': { backgroundColor: '#bae6fd', borderRadius: '4px', padding: '0px 6px' },
  'highlight-deep-red': { backgroundColor: '#be123c', color: '#ffffff', borderRadius: '4px', padding: '0px 6px' },
  'highlight-deep-blue': { backgroundColor: '#1d4ed8', color: '#ffffff', borderRadius: '4px', padding: '0px 6px' },
  'highlight-deep-green': { backgroundColor: '#047857', color: '#ffffff', borderRadius: '4px', padding: '0px 6px' },
  'highlight-deep-purple': { backgroundColor: '#6b21a8', color: '#ffffff', borderRadius: '4px', padding: '0px 6px' },
  'highlight-deep-orange': { backgroundColor: '#c2410c', color: '#ffffff', borderRadius: '4px', padding: '0px 6px' },
  'highlight-deep-pink': { backgroundColor: '#be185d', color: '#ffffff', borderRadius: '4px', padding: '0px 6px' },
  'highlight-deep-cyan': { backgroundColor: '#0369a1', color: '#ffffff', borderRadius: '4px', padding: '0px 6px' },
  'highlight-deep-yellow': { backgroundColor: '#b45309', color: '#ffffff', borderRadius: '4px', padding: '0px 6px' },
  'underline-red': { borderBottom: '4px solid #e11d48' },
  'underline-blue': { borderBottom: '4px solid #1d4ed8' },
  'underline-green': { borderBottom: '4px solid #10b981' },
  'underline-black': { borderBottom: '4px solid #000000' },
  'underline-purple': { borderBottom: '4px solid #7e22ce' },
  'underline-orange': { borderBottom: '4px solid #ea580c' },
  'underline-cyan': { borderBottom: '4px solid #0284c7' },
  'underline-fuchsia': { borderBottom: '4px solid #c026d3' },
  'underline-pink': { borderBottom: '4px solid #db2777' },
  'underline-yellow': { borderBottom: '4px solid #d97706' },
  'underline-lime': { borderBottom: '4px solid #65a30d' },
  'underline-double-red': { borderBottom: '5px double #e11d48' },
  'underline-double-blue': { borderBottom: '5px double #1d4ed8' },
  'underline-double-green': { borderBottom: '5px double #10b981' },
  'underline-double-black': { borderBottom: '5px double #000000' },
  'underline-double-purple': { borderBottom: '5px double #7e22ce' },
  'underline-double-cyan': { borderBottom: '5px double #0284c7' },
  'underline-double-fuchsia': { borderBottom: '5px double #c026d3' },
  'underline-double-orange': { borderBottom: '5px double #ea580c' },
  'underline-dashed-red': { borderBottom: '3px dashed #e11d48' },
  'underline-dashed-blue': { borderBottom: '3px dashed #1d4ed8' },
  'underline-dashed-green': { borderBottom: '3px dashed #10b981' },
  'underline-dashed-black': { borderBottom: '3px dashed #000000' },
  'underline-dashed-purple': { borderBottom: '3px dashed #7e22ce' },
  'underline-dashed-cyan': { borderBottom: '3px dashed #0284c7' },
  'underline-dotted-red': { borderBottom: '4px dotted #e11d48' },
  'underline-dotted-blue': { borderBottom: '4px dotted #1d4ed8' },
  'underline-dotted-green': { borderBottom: '4px dotted #10b981' },
  'underline-dotted-black': { borderBottom: '4px dotted #000000' },
  'underline-dotted-purple': { borderBottom: '4px dotted #7e22ce' },
  'underline-dotted-fuchsia': { borderBottom: '4px dotted #c026d3' },
  'underline-thick-red': { borderBottom: '6px solid #e11d48' },
  'underline-thick-blue': { borderBottom: '6px solid #1d4ed8' },
  'underline-thick-green': { borderBottom: '6px solid #10b981' },
  'underline-thick-purple': { borderBottom: '6px solid #7e22ce' },
  'underline-thick-yellow': { borderBottom: '6px solid #d97706' },
  'bold': { fontWeight: '700' },
  'font-bold': { fontWeight: '700' },
  'italic': { fontStyle: 'italic' },
  'font-normal': { fontWeight: '400' },
  'absolute': { position: 'absolute' },
  'relative': { position: 'relative' },
  'static': { position: 'static' },
  'fixed': { position: 'fixed' },
  'p-0': { padding: '0px' },
  'p-1': { padding: '4px' },
  'p-2': { padding: '8px' },
  'p-3': { padding: '12px' },
  'p-4': { padding: '16px' },
  'p-5': { padding: '20px' },
  'px-1': { paddingLeft: '4px', paddingRight: '4px' },
  'px-2': { paddingLeft: '8px', paddingRight: '8px' },
  'px-3': { paddingLeft: '12px', paddingRight: '12px' },
  'px-4': { paddingLeft: '16px', paddingRight: '16px' },
  'py-1': { paddingTop: '4px', paddingBottom: '4px' },
  'py-2': { paddingTop: '8px', paddingBottom: '8px' },
  'py-3': { paddingTop: '12px', paddingBottom: '12px' },
  'py-4': { paddingTop: '16px', paddingBottom: '16px' },
  'm-0': { margin: '0px' },
  'm-1': { margin: '4px' },
  'm-2': { margin: '8px' },
  'm-3': { margin: '12px' },
  'm-4': { margin: '16px' },
  'mx-auto': { marginLeft: 'auto', marginRight: 'auto' },
  'border-0': { borderWidth: '0px' },
  'border': { border: '2px solid #e5e7eb' },
  'border-1': { borderWidth: '1px' },
  'border-2': { borderWidth: '2px' },
  'border-3': { borderWidth: '3px' },
  'border-4': { borderWidth: '4px' },
  'border-6': { borderWidth: '6px' },
  'border-8': { borderWidth: '8px' },
  'border-black': { borderColor: '#000000' },
  'border-white': { borderColor: '#ffffff' },
  'border-gray': { borderColor: '#9ca3af' },
  'border-red': { borderColor: '#e11d48' },
  'border-blue': { borderColor: '#1d4ed8' },
  'border-green': { borderColor: '#10b981' },
  'border-purple': { borderColor: '#7e22ce' },
  'border-orange': { borderColor: '#ea580c' },
  'border-cyan': { borderColor: '#0284c7' },
  'border-fuchsia': { borderColor: '#c026d3' },
  'border-pink': { borderColor: '#db2777' },
  'border-yellow': { borderColor: '#d97706' },
  'border-solid': { borderStyle: 'solid' },
  'border-dashed': { borderStyle: 'dashed' },
  'border-dotted': { borderStyle: 'dotted' },
  'border-double': { borderStyle: 'double' },
  'border-dashed-blue': { border: '3px dashed #1d4ed8' },
  'border-dashed-red': { border: '3px dashed #e11d48' },
  'border-dashed-green': { border: '3px dashed #10b981' },
  'border-double-black': { border: '5px double #000000' },
  'rounded-none': { borderRadius: '0px' },
  'rounded-sm': { borderRadius: '2px' },
  'rounded': { borderRadius: '4px' },
  'rounded-md': { borderRadius: '6px' },
  'rounded-lg': { borderRadius: '8px' },
  'rounded-xl': { borderRadius: '12px' },
  'rounded-2xl': { borderRadius: '16px' },
  'rounded-3xl': { borderRadius: '24px' },
  'rounded-full': { borderRadius: '9999px' },
  'w-auto': { width: 'auto' },
  'w-full': { width: '100%' },
  'w-10': { width: '10px' },
  'w-20': { width: '20px' },
  'w-30': { width: '30px' },
  'w-40': { width: '40px' },
  'w-50': { width: '50px' },
  'w-60': { width: '60px' },
  'w-70': { width: '70px' },
  'w-80': { width: '80px' },
  'w-90': { width: '90px' },
  'w-100': { width: '100px' },
  'w-120': { width: '120px' },
  'w-140': { width: '140px' },
  'w-160': { width: '160px' },
  'w-180': { width: '180px' },
  'w-200': { width: '200px' },
  'w-220': { width: '220px' },
  'w-240': { width: '240px' },
  'w-260': { width: '260px' },
  'w-280': { width: '280px' },
  'w-300': { width: '300px' },
  'w-320': { width: '320px' },
  'w-340': { width: '340px' },
  'w-360': { width: '360px' },
  'w-380': { width: '380px' },
  'w-400': { width: '400px' },
  'w-450': { width: '450px' },
  'w-500': { width: '500px' },
  'w-550': { width: '550px' },
  'w-600': { width: '600px' },
  'w-650': { width: '650px' },
  'w-700': { width: '700px' },
  'w-750': { width: '750px' },
  'w-800': { width: '800px' },
  'w-900': { width: '900px' },
  'w-1000': { width: '1000px' },
  'w-1100': { width: '1100px' },
  'w-1200': { width: '1200px' },
  'w-1350': { width: '1350px' },
  'w-1400': { width: '1400px' },
  'w-1450': { width: '1450px' },
  'w-1500': { width: '1500px' },
  'w-1550': { width: '1550px' },
  'w-1600': { width: '1600px' },
  'w-1650': { width: '1650px' },
  'w-1700': { width: '1700px' },
  'w-1750': { width: '1750px' },
  'w-1800': { width: '1800px' },
  'w-1850': { width: '1850px' },
  'w-1900': { width: '1900px' },
  'w-1920': { width: '1920px' },
  'h-auto': { height: 'auto' },
  'h-full': { height: '100%' },
  'h-10': { height: '10px' },
  'h-20': { height: '20px' },
  'h-30': { height: '30px' },
  'h-40': { height: '40px' },
  'h-50': { height: '50px' },
  'h-60': { height: '60px' },
  'h-70': { height: '70px' },
  'h-80': { height: '80px' },
  'h-90': { height: '90px' },
  'h-100': { height: '100px' },
  'h-120': { height: '120px' },
  'h-140': { height: '140px' },
  'h-160': { height: '160px' },
  'h-180': { height: '180px' },
  'h-200': { height: '200px' },
  'h-220': { height: '220px' },
  'h-240': { height: '240px' },
  'h-260': { height: '260px' },
  'h-300': { height: '300px' },
  'h-320': { height: '320px' },
  'h-340': { height: '340px' },
  'h-360': { height: '360px' },
  'h-380': { height: '380px' },
  'h-400': { height: '400px' },
  'h-450': { height: '450px' },
  'h-500': { height: '500px' },
  'h-550': { height: '550px' },
  'h-600': { height: '600px' },
  'h-650': { height: '650px' },
  'h-700': { height: '700px' },
  'h-750': { height: '750px' },
  'h-800': { height: '800px' },
  'object-contain': { objectFit: 'contain' },
  'object-cover': { objectFit: 'cover' },
  'object-fill': { objectFit: 'fill' },
  'font-kalam': { fontFamily: "'Kalam', cursive, sans-serif" },
  'font-caveat': { fontFamily: "'Caveat', cursive, sans-serif" },
  'font-patrick': { fontFamily: "'Patrick Hand', cursive, sans-serif" },
  'font-architect': { fontFamily: "'Architects Daughter', cursive, sans-serif" },
  'font-delius': { fontFamily: "'Delius', cursive, sans-serif" },
  'font-fredoka': { fontFamily: "'Fredoka', sans-serif" },
  'font-comfortaa': { fontFamily: "'Comfortaa', sans-serif" },
  'font-shadow': { fontFamily: "'Shadows Into Light', cursive, sans-serif" },
  'font-amatic': { fontFamily: "'Amatic SC', cursive, sans-serif" },
  'font-marker': { fontFamily: "'Permanent Marker', cursive, sans-serif" },
  'font-indie': { fontFamily: "'Indie Flower', cursive, sans-serif" },
  'font-another-hand': { fontFamily: "'Just Another Hand', cursive, sans-serif" },
  'font-rock-salt': { fontFamily: "'Rock Salt', cursive, sans-serif" },
  'font-quicksand': { fontFamily: "'Quicksand', sans-serif" },
  'font-pangolin': { fontFamily: "'Pangolin', cursive, sans-serif" },
  'z-auto': { zIndex: 'auto' },
  'z-0': { zIndex: '0' },
  'z-1': { zIndex: '1' },
  'z-2': { zIndex: '2' },
  'z-5': { zIndex: '5' },
  'z-10': { zIndex: '10' },
  'z-20': { zIndex: '20' },
  'z-30': { zIndex: '30' },
  'z-40': { zIndex: '40' },
  'z-50': { zIndex: '50' },
  'z-100': { zIndex: '100' },
  'z-999': { zIndex: '999' },
  'leading-none': { lineHeight: '1' },
  'leading-tight': { lineHeight: '1.25' },
  'leading-snug': { lineHeight: '1.375' },
  'leading-normal': { lineHeight: '1.5' },
  'leading-relaxed': { lineHeight: '1.625' },
  'leading-loose': { lineHeight: '2' },
  'leading-40': { lineHeight: '40px' },
  'leading-50': { lineHeight: '50px' },
  'leading-60': { lineHeight: '60px' },
  'leading-70': { lineHeight: '70px' },
  'leading-80': { lineHeight: '80px' },
  'leading-90': { lineHeight: '90px' },
  'leading-100': { lineHeight: '100px' }
};

/**
 * 🎯 parseClassNameToStyle
 * এই মেথডটি যেকোনো স্পেস-সেপারেটেড ক্লাস স্ট্রিং (যেমন: "font-kalam top-80 left-100 text-red") রিড করবে, 
 * এবং লুপ চালিয়ে পিক্সেল গ্রিড লক লজিক ও স্ট্যাটিক সিএসএস ম্যাপ মার্জ করে একটি পিউর স্টাইল অবজেক্ট রিটার্ন করবে।
 */
export const parseClassNameToStyle = (className = '') => {
  if (!className) return {};

  const classes = className.split(/\s+/).filter(Boolean);
  const resolvedStyle = {};

  classes.forEach((cls) => {
    // ১. স্ট্যাটিক ম্যাপ থেকে হুবহু ম্যাচ হওয়া রুলস মার্জ করা হচ্ছে
    if (MASTER_STYLE_MAP[cls]) {
      Object.assign(resolvedStyle, MASTER_STYLE_MAP[cls]);
      return;
    }

    // ২. ডাইনামিক গ্রিড লক লজিক (Top, Left, Width, Height, Line-Height পিক্সেল ম্যাপিং)
    
    // --- TOP POSITIONS ---
    if (cls.startsWith('top-')) {
      const val = parseInt(cls.substring(4), 10);
      if (!isNaN(val)) resolvedStyle.top = `${val}px`;
      return;
    }

    // --- LEFT POSITIONS ---
    if (cls.startsWith('left-')) {
      const val = parseInt(cls.substring(5), 10);
      if (!isNaN(val)) resolvedStyle.left = `${val}px`;
      return;
    }

    // --- WIDTH UTILITIES ---
    if (cls.startsWith('w-')) {
      const val = parseInt(cls.substring(2), 10);
      if (!isNaN(val)) resolvedStyle.width = `${val}px`;
      return;
    }

    // --- HEIGHT UTILITIES ---
    if (cls.startsWith('h-')) {
      const val = parseInt(cls.substring(2), 10);
      if (!isNaN(val)) resolvedStyle.height = `${val}px`;
      return;
    }

    // --- CUSTOM PIXEL LINE-HEIGHTS ---
    if (cls.startsWith('leading-')) {
      const val = parseInt(cls.substring(8), 10);
      if (!isNaN(val)) resolvedStyle.lineHeight = `${val}px`;
      return;
    }
  });

  return resolvedStyle;
};